# Generated by Django 2.2 on 2019-04-20 18:01

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190420_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=task.models.order_number, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
