# Generated by Django 2.2 on 2019-04-22 07:22

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190420_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=task.models.order_number),
        ),
    ]
